export const references = {
  merck: { title: "Blood Transfusions in Dogs and Cats", organization: "MSD/Merck Veterinary Manual · Shauna Blois", year: 2026, sourceType: "reference-table", url: "https://www.merckvetmanual.com/circulatory-system/blood-groups-and-blood-transfusions-in-dogs-and-cats/blood-transfusions-in-dogs-and-cats", supports: "RBC mass balance, EBV ranges, plasma dose, typing, monitoring and platelet dose; March 2026." },
  isfm: { title: "2021 ISFM Consensus Guidelines on the Collection and Administration of Blood and Blood Products in Cats", organization: "Taylor, Spada, Callan et al. · JFMS", year: 2021, sourceType: "consensus", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10741281/", doi: "10.1177/1098612X211007071", supports: "Feline donor assessment, collection, anticoagulants, empirical estimate and compatibility." },
  tracs: { title: "AVHTM TRACS Part 2: Prevention and monitoring", organization: "Davidow et al. · JVECC", year: 2021, sourceType: "consensus", url: "https://doi.org/10.1111/vec.13045", doi: "10.1111/vec.13045", supports: "Administration, filters, TACO, monitoring and massive transfusion." },
  acvim: { title: "Update on Canine and Feline Blood Donor Screening for Blood-Borne Pathogens", organization: "Wardrop et al. · JVIM", year: 2016, sourceType: "consensus", url: "https://doi.org/10.1111/jvim.13823", doi: "10.1111/jvim.13823", supports: "Region/exposure-dependent screening and at least annual retesting." },
  italy: { title: "Italian national veterinary blood guideline · 60/CSR", organization: "Conferenza Stato-Regioni · 17 April 2025", year: 2025, sourceType: "guideline", url: "https://www.gazzettaufficiale.it/eli/gu/2025/05/13/109/sg/pdf", supports: "Canine collection profile, Hb references and alternative feline protocol." },
  cornell: { title: "Comparative Coagulation — Transfusion Guidelines", organization: "Cornell University College of Veterinary Medicine", year: null, sourceType: "reference-table", url: "https://www.vet.cornell.edu/animal-health-diagnostic-center/laboratories/comparative-coagulation/clinical-topics/transfusion-guidelines", supports: "Common RBC doses, alternative plasma dose and cryoprecipitate." },
  pbbDog: { title: "Canine donor criteria", organization: "Pet Blood Bank UK", year: null, sourceType: "blood-bank-policy", url: "https://www.petbloodbankuk.org/pet-owners/dog-blood-donation/can-your-dog-donate-blood/", supports: "Active blood-bank screening policy, not a universal weight minimum." },
  pbbCat: { title: "Feline donor criteria", organization: "Pet Blood Bank UK", year: 2026, sourceType: "blood-bank-policy", url: "https://www.petbloodbankuk.org/pet-owners/cat-blood-donation/", supports: "Current blood-bank policy differs from the selected ISFM collection profile; not a source for the 12 mL/kg default." },
  prediction: { title: "Assessment of five formulae to predict post-transfusion packed cell volume in cats", organization: "Kisielewicz et al. · JFMS", year: 2014, sourceType: "research", url: "https://pubmed.ncbi.nlm.nih.gov/24393778/", supports: "PCV prediction limitations." },
} as const;
export type SourceId = keyof typeof references;
