// English prototype copy. Add locale maps here rather than translating components.
export const copy = {
  title: 'Parasite Selector',
  subtitle: 'Compare parasite coverage and help select appropriate preventative products.',
  prototype: 'Prototype — Malaysian product-label information has not yet been verified. “?” means unknown, not no coverage.',
  species: 'Species', dog: 'Dog', cat: 'Cat', client: 'Client View', vet: 'Vet View',
  view: 'Information view', back: '← All modes',
  modes: [
    { id: 'find', title: 'Find Protection', description: 'Choose the parasites you want covered.' },
    { id: 'compare', title: 'Compare Products', description: 'Compare parasite coverage between selected products.' },
    { id: 'identify', title: 'Identify Parasite', description: 'Help determine what the client means by flea, tick, mite or worm.' },
  ],
  coming: 'Parasite identification guide — coming next.',
  groups: { ecto: 'Ectoparasites', endo: 'Endoparasites' },
  matches: { full: 'Full match', partial: 'Partial match', unverified: 'Coverage unverified', none: 'No match' },
  matchHelp: { full: 'Every selected parasite is marked covered. Check label details.', partial: 'Some coverage is confirmed or indication-specific; review gaps and unknowns.', unverified: 'No full coverage confirmed for the selection. Verification is needed.', none: 'None of the selected parasites is covered in the dataset.' },
  statuses: {
    covered: { symbol: '✅', label: 'Covered' },
    not_covered: { symbol: '❌', label: 'Not covered' },
    partial: { symbol: '🟨', label: 'Partial / specific indication' },
    unverified: { symbol: '?', label: 'Unverified' },
  },
  selectParasites: 'Select parasites', selectPrompt: 'Choose one or more parasites to see matching products.',
  selectProducts: 'Select products to compare', comparePrompt: 'Select 2–5 products. The table updates immediately.',
  compareEmpty: 'Choose a product to start comparing.', limit: 'Five products selected. Remove one to add another.',
  common: 'Common', all: 'All', scope: 'Parasites shown', differences: 'Show differences only',
  same: 'No coverage-status differences in this view. Matching “?” statuses do not confirm equal protection.',
  matrix: 'Product coverage comparison', product: 'Product', scroll: 'Scroll sideways to compare. Select a product name for details.',
  missing: 'Missing coverage', limited: 'Specific indication — review details', unknown: 'Coverage not yet verified',
  details: 'View details', close: 'Close product details', notVerified: 'Not yet verified',
  coverage: 'Parasite coverage', sources: 'Sources', warnings: 'Important cautions',
  fields: { activeIngredients: 'Active ingredients', formulation: 'Formulation', route: 'Route', interval: 'Typical interval', minimumAge: 'Minimum age', minimumWeight: 'Minimum weight', pregnancyLactation: 'Pregnancy / lactation', notes: 'Additional notes' },
  indication: 'Indication', indications: { treat: 'Treatment', prevent: 'Prevention', control: 'Control', treat_and_prevent: 'Treatment and prevention' },
  sourceDate: 'Verified', sourceIds: 'Source references',
  disclaimer: 'Decision-support prototype, not a prescription. Confirm the species-specific Malaysian product label before selecting or using a product. Coverage categories do not establish dosing, suitability or safety.',
} as const;
