"use client";
import { useMemo, useState } from "react";
import { addDays, calculateDaysRemaining, dogSize, formatDate, type FetalMeasurement, type FetalSpecies } from "./calculations";

const today = new Date().toISOString().slice(0, 10);
export default function FetalAge() {
  const [species, setSpecies] = useState<FetalSpecies>("dog"); const [weight, setWeight] = useState(""); const [measurement, setMeasurement] = useState<FetalMeasurement>("icc"); const [values, setValues] = useState([""]); const [scanDate, setScanDate] = useState(today);
  const weightKg = Number(weight); const size = species === "dog" ? dogSize(weightKg) : null;
  const result = useMemo(() => { const nums = values.map(Number).filter(value => Number.isFinite(value) && value > 0); if (!nums.length) return null; const mean = nums.reduce((a, b) => a + b, 0) / nums.length; const days = calculateDaysRemaining(species, measurement, mean, weightKg); if (days === null) return null; const range = species === "cat" ? (measurement === "icc" ? [19, 37] : [38, 65]) : (size === "small" ? (measurement === "icc" ? [21, 42] : [1, 37]) : size === "medium" ? (measurement === "icc" ? [21, 42] : [1, 37]) : size === "large" ? (measurement === "icc" ? [26, 42] : [2, 30]) : (measurement === "icc" ? [25, 40] : [1, 35])); const gestationalDay = 65 - days; const valid = days >= 0 && days <= 50; const within = days >= range[0] && days <= range[1]; return { mean, days, gestationalDay, within, valid, date: addDays(new Date(`${scanDate}T12:00:00`), days) }; }, [values, species, measurement, weightKg, size, scanDate]);
  const updateValue = (index: number, value: string) => setValues(current => current.map((item, i) => i === index ? value : item));
  return <main className="toolkit-workspace fetal-age-workspace"><div className="toolkit-intro"><span className="fetal-wip">WORK IN PROGRESS</span><h1>Ultrasound Fetal Age Calculator</h1><p>Estimate gestational stage and approximate parturition timing from fetal measurements.</p></div>
    <section className="clinical-section fetal-age-card"><h2>Patient &amp; scan</h2><fieldset className="species-picker"><legend>Species</legend><div className="segmented"><button type="button" className={species === "dog" ? "active" : ""} aria-pressed={species === "dog"} onClick={() => { setSpecies("dog"); setValues([""]); }}><span className="species-emoji" aria-hidden="true">🐕</span>Dog</button><button type="button" className={species === "cat" ? "active" : ""} aria-pressed={species === "cat"} onClick={() => { setSpecies("cat"); setValues([""]); }}><span className="species-emoji" aria-hidden="true">🐈</span>Cat</button></div></fieldset>
      {species === "dog" && <label className="tx-field"><span>Maternal weight</span><div className="unit-input"><input type="number" inputMode="decimal" min="0" step="any" value={weight} onChange={e => setWeight(e.target.value)} /><span>kg</span></div>{size && <small>{weightKg} kg · {size} dog</small>}</label>}
      <label className="tx-field"><span>Measurement</span><select value={measurement} onChange={e => setMeasurement(e.target.value as FetalMeasurement)}><option value="icc">ICC — early pregnancy</option><option value="bpd">BPD — later pregnancy</option></select><small>{measurement === "icc" ? "Inner Chorionic Cavity" : "Biparietal Diameter"}</small></label>
      <div className="fetal-measurements"><span className="field-label">Ultrasound measurement(s) <small>mm</small></span>{values.map((value, index) => <div className="fetal-value-row" key={index}><label><span>Fetus {index + 1}</span><input type="number" inputMode="decimal" min="0" step="any" value={value} onChange={e => updateValue(index, e.target.value)} /></label>{values.length > 1 && <button type="button" className="text-button" onClick={() => setValues(current => current.filter((_, i) => i !== index))}>Remove</button>}</div>)}<button type="button" className="text-button" onClick={() => setValues(current => [...current, ""])}>+ Add fetus</button></div>
      <label className="tx-field"><span>Scan date</span><input type="date" value={scanDate} onChange={e => setScanDate(e.target.value)} /></label>
    </section>
    <section className={`clinical-section fetal-result ${result && !result.valid ? "fetal-result-invalid" : ""}`} aria-live="polite"><h2>🐣 Estimated fetal age</h2>{!result ? <p className="section-pending">Enter a valid measurement to estimate timing.</p> : !result.valid ? <p className="fetal-alert">Measurement is outside the useful range for this formula. Confirm measurement type and technique.</p> : <><div className="fetal-result-grid"><div><span>{species === "dog" ? "Estimated gestational age" : "Approximate gestational stage"}</span><strong>≈ Day {Math.max(0, Math.round(result.gestationalDay))}</strong></div><div><span>About</span><strong>{Math.max(0, Math.round(result.days))} days remaining</strong></div><div><span>Estimated parturition</span><strong>{formatDate(result.date)}</strong></div><div><span>Expected clinical window</span><strong>{result.within ? `${formatDate(addDays(result.date, -2))} – ${formatDate(addDays(result.date, 2))}` : "Use cautiously"}</strong></div></div><p className="fetal-method">{measurement.toUpperCase()} · {species === "dog" ? `${size} dog` : "general feline formula"} · Mean measurement: {result.mean.toFixed(2)} mm</p>{!result.within && <p className="fetal-alert fetal-alert-amber">⚠ Outside the main published validation range. Interpret the estimate cautiously.</p>}{values.filter(v => Number(v) > 0).length === 1 && <p className="fetal-note">Single-fetus measurement. Multiple fetuses are preferable when available.</p>}</>}</section>
    <details className="fetal-details"><summary>Ultrasound Reference</summary><div className="fetal-reference"><h3>ICC — Inner Chorionic Cavity</h3><p>Obtain the maximal transverse gestational-sac plane, measure inner wall to inner wall in two perpendicular directions, average them, and enter the mean in mm.</p><h3>BPD — Biparietal Diameter</h3><p>Use a correctly aligned fetal head plane and measure the widest distance across the symmetrical parietal bones in mm.</p><h3>{species === "dog" ? "Dog" : "Cat"} developmental landmarks</h3><p>{species === "dog" ? "~Day 19–21 sacs · ~Day 23–26 cardiac activity · ~Day 35–39 bladder/stomach · ~Day 48–54 intestinal layering." : "~Day 10 sacs · ~Day 15–17 embryo and cardiac activity · ~Day 29–30 biometry increasingly useful · ~Day 52–56 intestinal layering."}</p></div></details>
    <details className="fetal-details"><summary>Evidence &amp; References</summary><div className="fetal-reference"><p>Luvoni &amp; Grioni (2000), <em>J Small Anim Pract</em>.</p><p>Beccaglia &amp; Luvoni (2006), <em>J Small Anim Pract</em>.</p><p>Beccaglia et al. (2016), <em>Reprod Domest Anim</em>. doi:10.1111/rda.12782</p><p>Alonge et al. (2016), <em>J Small Anim Pract</em>. doi:10.1111/jsap.12534</p><p>Górka et al. (2025), <em>Theriogenology</em>. doi:10.1016/j.theriogenology.2024.10.030</p></div></details>
    <p className="fetal-disclaimer">Ultrasonographic fetometry provides an estimate of gestational stage and parturition timing. Accuracy varies with gestational stage, breed, litter characteristics, fetal positioning, measurement technique and operator experience. This tool supports veterinary judgement and does not replace clinical assessment.</p>
  </main>;
}
